baseURL = "https://hrasto.github.io"
title = "Rastislav Hronský"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Rastislav's personal website"
  copyright = "Copyright © 2026 Rastislav Hronsky"
  email = "mail@rhronsky.com"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 1
    post = ","

  [[menu.main]]
    identifier = "publications"
    name = "publications"
    title = "publications"
    url = "/publications/"
    weight = 2
    post = ","

  [[menu.main]]
    identifier = "cv"
    name = "cv"
    title = "cv"
    url = "/cv/"
    weight = 3

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
